### ISSUE TITLE
background-fetch and BackgroundSync

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/background-fetch#140]
Hi @jakearchibald, sorry for the silly question... what's the relationship between BackgroundSync and background-fetch? Is background-fetch still something you'd still like to see incubated (just checking if this is still an active incubation)?

**Comment by jakearchibald** [comment]
It isn't a silly question. In fact there's a section in the explainer about it: https://github.com/WICG/background-fetch#relation-to-one-off-background-sync

Background fetch is very much still active. Mozilla and Apple have expressed that they'd prefer to work on this spec rather than background sync. We may also explore altering background-fetch to cater for the use-cases of one-off background sync https://github.com/WICG/BackgroundSync/issues/156.

**Comment by marcoscaceres** [comment]
Thanks for the additional pointers. Ok, let's see where the conversations end up... hopefully these two incubations will merge into a happy place.
