### ISSUE TITLE
When should backgroundfetchfailed fire?

### ISSUE THREAD

**Issue by jakearchibald** [WICG/background-fetch#24]
Does it fire as soon as possible, and discard any in-progress fetches? Or does it wait for all fetched to settle?

On one hand, failing fast is nice, because it's fast, but you might end up throwing away a 99% downloaded movie because a piece of metadata 404'd.

**Comment by jenharkness** [comment]
I think we have to assume that the developer wants all the files downloaded. So if some of them fail, they will retry those files. As long as they're going to do a retry, we should just keep downloading the ones which haven't failed to reduce the number of files in the eventual retry and to preserve any progress that non-failed files have made.

For the developer who wants all or nothing BackgroundFetch, they can always query for status and find out if any of the individual requests have failed. If this becomes a common use case, we could always add a new event that notifies the service worker that an individual request has failed (so that a developer could abort the rest) but doesn't abort unless the developer takes an action.

**Comment by jakearchibald** [comment]
Agreed!
