### ISSUE TITLE
Naming for the requests returned in  BackgroundFetchFailedEvent and BackgroundFetchedEvent

### ISSUE THREAD

**Issue by jenharkness** [WICG/background-fetch#34]
I had been thinking that the backgroundfetchfail could return a set of results, only some of which failed and some of which succeeded. However, the attribute on the event is called "failedFetches". On the backgroundfetched event, the list of result/response pairs is called "completedFetches".

Proposal: Use "completedFetches" for the attribute on both BackgroundFetchedEvent and BackgroundFetchFailedEvent. Then embed the success or failure of each request in the response?

This may be a moot point depending on the outcome of https://github.com/WICG/background-fetch/issues/23.

**Comment by mounirlamouri** [comment]
It's unclear from the spec what's the difference between `backgroundfetched` and `backgroundfetchfail`. It might help figure out the right naming here. I agree that consistent name would be better because we use the same type anyway. Though, would it make sense to have generic name such as `fetches` given that the event name should be enough as a context?

**Comment by johnmellor** [comment]
How about merging the events (#23) and having both `successfulFetches` and `failedFetches` lists as properties on the event?

**Comment by jakearchibald** [comment]
@johnmellor you lose the ordering of items that way. Dunno how important that is.

**Comment by jakearchibald** [comment]
Going to rename this property `fetches` as @mounirlamouri suggested.

**Comment by jakearchibald** [comment]
Fixed https://github.com/WICG/background-fetch/commit/5d399383ed0b2c69c88bfb74e98c506c2688a433

This also resulted in renaming `bgFetchJob.fetches` to `beFetchJob.activeFetches`.
