### ISSUE TITLE
In-document progress events

### ISSUE THREAD

**Issue by beverloo** [WICG/background-fetch#48]
A common use case will be to display the transfer progress of a Background Fetch on a page. Right now that'd require the developer to (a) know the total download size, and (b) iterate over all `activeFetches` to read the length of the bodies of those that have completed. That's super expensive and complicated.

There's not much we can do about (a), but we can make (b) far more convenient:

```webidl
interface BackgroundFetchRegistration : EventTarget {
    // Exposes the number of bytes that have been downloaded so far.
    readonly attribute long totalDownloadedSize;

    // Will be fired _at some frequency_ when progress happens.
    [Exposed=Window] attribute EventHandler onprogress;
}
```

(On a tangent, do we need something similar for `totalUploadedSize`?)

I guess the event type could just be a simple event without properties, as the developer can re-read `totalDownloadSize` and `totalDownloadedSize` from the `BackgroundFetchRegistration` instance. It also implies that we need to continue to return the same instances from e.g. `BackgroundFetchManager.get()` instead of creating new ones every time, and keep them updated. How would we define that? Would we be expected to keep updating `totalDownloadedSize` without event listeners?

**Comment by jakearchibald** [comment]
How about:

* `uploadTotal` – since we need to cache all request bodies before creating `BackgroundFetchRegistration`, we know what this is.
* `uploaded` – bytes uploaded.
* `downloadTotal` – the value provided at registration, or 0.
* `downloaded` – bytes successfully downloaded so far (which may decrease if a resource download is restarted).
* `onprogress` – for when these values update.

> I guess the event type could just be a simple event without properties

Agreed. `Event`.

> It also implies that we need to continue to return the same instances

Yeah, I'm not happy with how the service worker spec currently hand-waves this, so we have the opportunity to try to get it right here. I guess we should just create a map of these objects in the spec, associated with the environment settings object. We'd add them to the map the first time they're exposed (as in, first call to `.fetch` or `.get`), then ensure we return the same objects each time.

**Comment by jakearchibald** [comment]
Coming back to this, I'm worried that `uploaded`/`downloaded` could look a little booleany. Could add `bytes` to everything.

**Comment by beverloo** [comment]
+1 to your proposal, I don't have a major opinion about being explicit about the unit, but it  definitely is clearer. ( `BackgroundFetchRegistration.downloaded` feels booleany indeed.)

Returning the same objects for different calls seems good to me too.

**Comment by jakearchibald** [comment]
Going to reopen this, as I haven't hooked the events up yet.

**Comment by joeyparrish** [comment]
CC @vaage

Does this mean the progress events aren't hooked up in Chrome canary yet?  Or that there is spec text work going on for how to hook up these events?  Or both?

**Comment by beverloo** [comment]
No, Jake is talking about hooking up the events with the download/fetch algorithms in the spec, i.e. defining when we fire them.

Chrome Canary has implemented them already.

**Comment by joeyparrish** [comment]
Cool, thanks!

**Comment by jakearchibald** [comment]
This is now done.
