### ISSUE TITLE
Clarify aborting logic

### ISSUE THREAD

**Issue by johnmellor** [WICG/background-fetch#60]
There are a few oddities around aborting registrations:

1. Presumably [#background-fetch-registration-abort](https://wicg.github.io/background-fetch/#background-fetch-registration-abort) should include the same "TODO: terminate all related fetches." and "fire a functional event named backgroundfetchabort..." language as [#attempt-a-background-fetch](https://wicg.github.io/background-fetch/#attempt-a-background-fetch)?

2. The spec doesn't mention anywhere that users can trigger abort (except handwavingly in [#privacy-and-bandwidth-use](https://wicg.github.io/background-fetch/#privacy-and-bandwidth-use)), unless that's supposed to be implicit in "stream becomes errored" of [#attempt-a-background-fetch](https://wicg.github.io/background-fetch/#attempt-a-background-fetch)?

3. There's logic in [#attempt-a-background-fetch](https://wicg.github.io/background-fetch/#attempt-a-background-fetch) to avoid double-firing the `backgroundfetchabort` event if `abort()` was previously called. But it'll still fire a `backgroundfetchfail` event after `abort()` was successfully called. Is that desirable, or would it be better to squelch any further events after `abort()` has been called?

@jakearchibald is probably on it already :)

**Comment by jakearchibald** [comment]
> Presumably #background-fetch-registration-abort should include the same "TODO: terminate all related fetches." and "fire a functional event named backgroundfetchabort..." language as #attempt-a-background-fetch?

Ahh yes, it should terminate all related fetches. Clarified in https://github.com/WICG/background-fetch/commit/12bf83a3b6f0cbe23a82733ba9aaa9b1dbf0b997.

It doesn't need to fire `backgroundfetchabort`, that'll be picked up by [attempt a background fetch](https://wicg.github.io/background-fetch/#attempt-a-background-fetch-algorithm), as it'll handle the aborted fetches.

> The spec doesn't mention anywhere that users can trigger abort

Good point. I've clarified this a bit in https://github.com/WICG/background-fetch/commit/74fc2ca6071e728bd9ca8dfbb7e1d73cd31be5c4, but I'll revisit this when I spec terminating properly.

> There's logic in #attempt-a-background-fetch to avoid double-firing the backgroundfetchabort event if abort() was previously called. But it'll still fire a backgroundfetchfail event after abort() was successfully called.

My intent is that [attempt a background fetch](https://wicg.github.io/background-fetch/#attempt-a-background-fetch-algorithm) is the only place that will trigger the abort event. `backgroundfetchfail ` is part of an "otherwise", so it shouldn't be possible for both to happen.

**Comment by johnmellor** [comment]
Great, thanks! Presumably `*aborted* flag` and `*abort* flag` from those commits should be `[=response/aborted flag=]`?

**Comment by jakearchibald** [comment]
It's part of https://fetch.spec.whatwg.org/#concept-fetch-terminate. It's a little vague, hopefully we can deal with it as part of https://github.com/whatwg/fetch/issues/536#issuecomment-330482027.
