### ISSUE TITLE
backgroundfetchfail vs failed vs error

### ISSUE THREAD

**Issue by kenchris** [WICG/background-fetch#75]
In response to https://github.com/w3ctag/design-reviews/issues/279

In specs like the Generic Sensor spec we use onerror. I think error is more descriptive than fail

**Comment by jakearchibald** [comment]
The reason I went for "fail" rather than "error", is that the background fetch may error many times before ultimately succeeding. Eg, if the user goes offline part way through, potentially many streams will error, but the fetches will later be resumed.

My feelings aren't particularly strong here though.

**Comment by kenchris** [comment]
So it is an unrecoverable error?

So maybe both events should exists? or how can you act on the other errors today?

**Comment by jakearchibald** [comment]
> So it is an unrecoverable error?

Yeah, it's the case where the background fetch has failed.

> So maybe both events should exists? 

Spinning up the service worker in the background for each fetch hiccup seems like a privacy violation to me, and also a battery issue.

> or how can you act on the other errors today?

How would you want to act on them?

**Comment by jakearchibald** [comment]
Closing due to no response.
