### ISSUE TITLE
Download small files without user interaction makes them actually not abortable

### ISSUE THREAD

**Issue by kenchris** [WICG/background-fetch#77]
In response to https://github.com/w3ctag/design-reviews/issues/279

Explainer says:

> Some browsers can already start downloads without user interaction, but they're easily abortable. We're following the same pattern here.

but small files will often complete before the user can abort. It might make sense with a persistent UI, allowing to delete files downloaded like that, or block further downloads.

If further downloads are being blocked by user, maybe there should be an event for that. I also notice that many browsers will allow downloading one file, but not necessarily multiple files without user interaction

**Comment by jakearchibald** [comment]
The concern here is bandwidth usage in the background.

Bandwidth usage in the foreground isn't a new problem, so it isn't worth solving specifically for bgfetch.

The number of files downloaded isn't a concern, since it may never be user-visible. Many fetches vs one big fetch doesn't matter. This is also consistent with our storage APIs - the number of objects in an object store isn't the concern, it's the space used.

Background fetch can't have the concept of deleting files, since it's up to the developer what to do with them once the fetch is complete. Eg, if the file is read as text, split, and hidden across 20 object stores, 4 caches, 8 local storage keys, two websql databases etc etc how would we delete that 'file'?

https://wicg.github.io/background-fetch/#background-fetch-display mentions that a download may start in a paused state. It's up to the UA when to do this, but it seems like a good idea for downloads started in the background.

**AI**: It makes sense to provision for background fetch being blocked for an origin. In this case, `backgroundFetch.fetch(...)` should reject, or the aborted event should happen straight away. Not sure which yet.

**Comment by jakearchibald** [comment]
Closing this. The action item is being handled in #87.
