### ISSUE TITLE
Permission vs start paused / instant abort

### ISSUE THREAD

**Issue by jakearchibald** [WICG/background-fetch#87]
**Option 1:** Handle permissions using auto pause/abort.

This is what's currently spec'd.

There's no permission step built in. Instead, user agents that want to ask user permission should start the background fetch in paused state, or auto-abort the background fetch.

If the background fetch is initiated from a push message it may be hours until the user sees the 'prompt'. During this time the browser may be taken out of memory. If `bgFetch.fetch(…)` resolves before the user 'accepts' the download, this isn't a problem. The user can unpause or abort the download hours later, and service worker events are used to communicate progress.

Also, the developer only needs to listen to the abort event to react to "the user does not want this".

This is kinda similar to how `new Notification()` works. The constructor always returns, but it may immediately fire an error event.

However, it might be weird to accept the fetch if background fetch is set to auto-deny. It seems wasteful to consume all the requests only to immediately abort the process.

**Option 2:** Handle permission requests using auto pause. Reject if background fetch is set to auto-deny.

Like option 1, except we reject the `bgFetch.fetch(…)` call if the user agent is set to deny background fetches. We know this really quickly, so there isn't a page lifecycle concern. If the user needs to be prompted, resolve `bgFetch.fetch(…)` and start the download in a paused state.

This means the user needs to handle "the user does not want this" in two places, in the abort event, and in the rejects to `bgFetch.fetch(…)`. However, it's possible you won't want to react the same to these anyway.

We could reject with [`NotAllowedError`](https://heycam.github.io/webidl/#notallowederror), but this would be different to [`showNotification`](https://notifications.spec.whatwg.org/#dom-serviceworkerregistration-shownotification) which rejects with a `TypeError`.

I guess we could stick with `TypeError` and rely on https://w3c.github.io/permissions/ if the developer wants to figure out if it was a permission issue.

**Option 3**: Handle permissions as part of `bgFetch.fetch(…)`.

`bgFetch.fetch(…)` would not resolve until the user accepts the download. It would reject if permission is denied, including if permission is auto-denied.

This has the page lifecycle issues described above.

@beverloo @mugdhalakhani what do you think? I'm learning towards option 2.

**Comment by beverloo** [comment]
In my mind, rejecting the promise is very different from firing a `backgroundfetchabort` event -

  - Rejecting `fetch()` means that the Background Fetch couldn't be started at all, probably because permission couldn't be granted. The developer might want to consider alternative techniques, e.g. fall back to regular fetch. This code path would likely exist already to support browsers that don't implement Background Fetch.

  - Sending `backgroundfetchabort` means that the Background Fetch could be started, but was aborted by either the developer (`abort()`) or the user while it was in-progress. You wouldn't want to try again.

Following that, I'm leaning towards option 3.

#### Option 1

> If the background fetch is initiated from a push message it may be hours until the user sees the 'prompt'. 

I don't think we'll want to prompt at all in this case. 

We can't prompt if the user isn't looking at an active tab for that particular origin—they'd lack any sort of context for the request. Such context might still be missing when they do visit the site again: imagine navigating to YouTube, getting a permission prompt followed by an immediate download of a funny cat video. I'd be rather surprised, to say the least.

Instead, I think we should abort earlier so that the site can re-request download at a more appropriate time. That matches what we do for other background APIs, such as the Push API, the Notification API and Background Sync.

> This is kinda similar to how new Notification() works. The constructor always returns, but it may immediately fire an error event.

The notification constructor predates modern Promise (and permission!) based design patterns. Furthermore, it's not available in Service Workers, so it's not a paradigm developers would expect.

> It seems wasteful to consume all the requests only to immediately abort the process.

Yes, this is a concern. We wouldn't just have to consume the requests, but also store them (or at least move to a different worker/process) and create void Response objects to match them.

#### Option 2

> If the user needs to be prompted, resolve bgFetch.fetch(…) and start the download in a paused state.

One scenario we should consider here are users ignoring the prompt. They could potentially live for the lifetime of the frame, which means that we'd issue the `backgroundfetchabort` event _after_ the frame has been closed. This isn't a rare occurrence in other permission requests.

> We could reject with `NotAllowedError`, but this would be different to `showNotification` which rejects with a TypeError.

The [Push API](https://www.w3.org/TR/push-api/#dom-pushmanager-subscribe) rejects with a `NotAllowedError`, as does [Background Sync](https://wicg.github.io/BackgroundSync/spec/#dom-syncmanager-register). I find that a better pattern. (I recall @annevk preferred `TypeError` at the time?)

#### Option 3

> This has the page lifecycle issues described above.

If we match similar background enabled APIs and reject Background Fetch when (a) permission is needed, but (b) there isn't an open window, I think these lifecycle issues stop being an issue?

**Comment by jakearchibald** [comment]
**Option 1**

> We can't prompt if the user isn't looking at an active tab for that particular origin—they'd lack any sort of context for the request

The notification would be the context. Eg, if `amazing-podcast-app.com` is wanting to download 50mb, that's all the context I need. This could also be a touch point for the user to indicate they're happy for the origin to initiate downloads in the background.

> The notification constructor predates modern Promise (and permission!) based design patterns. Furthermore, it's not available in Service Workers, so it's not a paradigm developers would expect.

Fair enough. Background download is somewhat different because it's a long-running activity whose permission could be revoked while it's active. By this point we have already resolved the promises, so the abort event is really our only choice.

**Option 2**

> One scenario we should consider here are users ignoring the prompt. They could potentially live for the lifetime of the frame, which means that we'd issue the backgroundfetchabort event after the frame has been closed.

This sounds like an argument against option 2 & 3, or am I misunderstanding?

**Option 3**

> If we match similar background enabled APIs and reject Background Fetch when (a) permission is needed, but (b) there isn't an open window, I think these lifecycle issues stop being an issue?

But you also throw away compelling use-cases like "download latest issue/podcast/episode". Are we really happy with that?

**Comment by jakearchibald** [comment]
Current thinking:

Create a "background-fetch" permission on https://w3c.github.io/permissions/. If that's set to `"deny"`, then the `backgroundFetch.fetch()` call will reject. If that's set to `"prompt"`, the download should start in the paused state. If it's set to `"allow"` the download should just start. Does this work?

**Comment by mugdhalakhani** [comment]
Yeah, sounds good!
