### ISSUE TITLE
Why grouped fetches? Can we simplify?

### ISSUE THREAD

**Issue by travisleithead** [WICG/background-fetch#91]
In response to https://github.com/w3ctag/design-reviews/issues/279

I understand conceptually that you are trying to map multiple fetches into a group for display in a UI, but it seems like adding a lot of unnecessarily API complexity for something that could be much easier managed by the UI and a simpler API. Take, for example, if the `backgroundFetch.fetch` API just scheduled one request (not a group). A second call to the API with the same ID would be the signal for browser UI to automatically group these together into notification UI.

If the web dev wants to know and track things like totalBytes, and aggregate progress, that is logic they can code-up on their own, based on responses to progress events--probably that info is more interesting and useful to the user, rather than the developer.

I can see the flip-side is the potential for a lot more events since each background fetch would have a separate state-tracker, but the simplified programming modal justifies this extra noise in my mind (which can even be mitigated by the UA when multiple background fetch objects are in a "group" (of same-id).

**Comment by jakearchibald** [comment]
Types of actions that involve multiple fetches:

* A movie. Often stored as 1000s of files.
* An album.
* The level of a game.
* Uploading photos.

Single fetch vs multiple fetches:

**Pro:** Wouldn't need cache-like `matchAll` etc if we're only dealing with one request/response pair. Also wouldn't need `BackgroundFetchSettledFetch` etc.

**Pro:** Wouldn't need progress events. We'd just wait for `FetchObserver` and use that.

**Pro:** Wouldn't need `id`, as the URL should be unique enough.

**Con:** Grouping in the UI becomes really hard. Using ID as a grouper doesn't really seem good enough. What text/icons would the notification use? The first ones specified? The last?

**Con:** Cancelling becomes hard. If I'm fetching 1000s of files for a movie, what happens if the user cancels the download when I've only successfully added 100 files? Are they going to have to cancel multiple times?

**Con:** Presenting the user with the total download size before they accept the download becomes difficult. You'd probably need a separate permission API to request a download of a particular size for a given ID. But then we're back to a larger API surface.

**Con:** Getting the progress could become heavy. In the case of 1000s of files, that's a lot of I/O just to discover the amount downloaded.

**Con:** Service worker wakes up for each of these 1000s of files. This creates a major battery issue.

**Con:** Difficult to know if the fetch worked or failed. The developer will have to create an entry in IDB for each file they're expecting, and tick them off as each arrives, and check if all have arrived.

**Con:** Effort to cancel related downloads if one fails. Right now, if one fails, the rest are aborted. In the single file model, the developer will have to do this themselves, meaning the default path is keeping the radio awake and using more bandwidth.

I guess we could punt to web packaging for grouping, although this may be an issue for the movie case, both on the server, and potentially additional storage usage on the client during extraction. I guess we could solve some of that with more APIs, but that kinda defeats the aim here.

That said, I think our initial implementation will only support a single fetch, so I'd like to hear thoughts from @beverloo and @mugdhalakhani.

**Comment by beverloo** [comment]
It sounds like we agree on grouping to be critical for the user experience, so let me skip to two more technical arguments -

1. We wouldn't want to wake up the Service Worker for each individual file. That's super expensive (likely prohibitively so on mobile platforms) and often unnecessary. Some platforms have dedicated download managers, which allow for optimizing away the need for the browser to be alive entirely.

2. An API based on individual fetches could still optimize for grouping through methods like `abortById` and `progressForId`, but it'd be far more cumbersome to use and might lead to de facto libraries for working with Background Fetch. Jake's use-cases are accurate: developers will usually want to work with a _package_ rather than an _individual file_. The notable exception is streaming content, e.g. downloading a movie or uploading a series of photos, which is enabled through the methods on [`BackgroundFetchRegistration`](https://wicg.github.io/background-fetch/#background-fetch-registration).

Chrome's experimental implementation supports any number of fetches per background fetch registration. It doesn't significantly complicate our implementation as we'd want the grouping to be maintained anyway for both UI and scheduling reasons. It does avoid developers from having to do such work themselves, without impacting lower level capabilities.

**Comment by jakearchibald** [comment]
I think the main problem with "loose grouping" (just add things with the same ID) is the browser doesn't know when it has all the items. This makes user aborting really tricky.

**Comment by jakearchibald** [comment]
Closing this. Feel free to reopen with replies to the above points, further data, etc etc.
